project: 
  type: book

book:
  title: "CCT Data Science Group Procedures"
  # cover-image: cover.png
  search: true
  repo-url: https://github.com/cct-datascience/group-procedures
  repo-actions: [edit]
  chapters:
    - index.qmd
    - part: general-info.qmd
      chapters:
        - code-of-conduct.qmd
        - onboarding.qmd
    - part: "Group Processes"
      chapters:
        - project-management.qmd
        - annual-reviews.qmd
        - quarterly-meetings.qmd
        - sprint-planning.qmd
        - standups.qmd
        - hiring.qmd
    - part: "Group Programming"
      chapters:
        - drop-in-hours.qmd
        - incubator.qmd
        - workshops.qmd
    - part: "Resources"
      chapters: 
        - creating-r-packages.qmd
    - references.qmd

format:
  html:
    code-copy: true
    theme: 
      light: flatly
      dark: darkly

bibliography: references.bib