project: 
  type: book
  resources: robots.txt
execute: 
  freeze: auto
book:
  title: "CCT Data Science Group Procedures"
  doi: 10.5281/zenodo.10783692
  author:
  - name:
      given: Kristina
      family: Riemer
    orcid: 0000-0003-3802-3331
  - name:
      given: Kimberly. M.
      family: Huynh
  - name:
      given: Christophe
      family: Schnaufer
  - name:
      given: Julian
      family: Pistorius
    orcid: 0000-0002-3485-0084
  - name:
      given: Jorge. E.
      family: Barrios
  - name:
      given: Emily. J.
      family: Cain
  - name:
      given: Jessica
      family: Guo
    orcid: 0000-0002-9566-9182
  - name:
      given: Eric R.
      family: Scott
    orcid: 0000-0002-7430-7879
  - name:
      given: Renata
      family: Diaz
    orcid: 0000-0003-0803-4734
  - name:
      given: David S.
      family: LeBauer
    orcid: 0000-0001-7228-053X
  # cover-image: cover.png
  search: true
  site-url: https://cct-datascience.github.io/group-procedures/
  repo-url: https://github.com/cct-datascience/group-procedures
  repo-actions: [edit, issue, source]
  repo-link-target: "_blank" #causes rep-actions links to open in a new tab
  issue-url: https://github.com/cct-datascience/group-procedures/issues/new?template=suggest-edit.md
  chapters:
    - index.qmd
    - contributing.qmd
    - part: "General Information"
      chapters:
        - general-info.qmd
        - code-of-conduct.qmd
        - group-expectations.qmd
    - part: "Group Processes (Agile)"
      chapters:
        - project-management.qmd
        - regular-meetings.qmd
        - sprint-planning.qmd 
        - quarterly-meetings.qmd
        - annual-reviews.qmd
        - impact.qmd
    - part: "Group Procedures"
      chapters:
        - onboarding.qmd
        - group-communication.qmd
        - outreach-communication.qmd
        - getting-credit.qmd
        - hiring.qmd
        - professional-development.qmd
        - code-review.qmd
        - offboarding.qmd
    - part: "Group Programming"
      chapters:
        - drop-in-hours.qmd
        - incubator.qmd
        - workshops.qmd
        - consultations.qmd
    - part: "Resources"
      chapters: 
        - networking.qmd
        - software.qmd
        - use-gmail.qmd
    - part: "Technical Vignettes"
      chapters: 
        - vignettes_overview.qmd
        - publishing-to-web.qmd
        - creating-r-packages.qmd
        - spreadsheet-database-vignette.qmd
        - boxr.qmd
    - references.qmd

format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    code-copy: true
    theme: 
      light: flatly
      dark: darkly
      
editor: 
  markdown:
    wrap: sentence
    canonical: true
    
bibliography: references.bib
