project: 
  type: book

book:
  title: "CCT Data Science Group Procedures"
  # cover-image: cover.png
  search: true
  repo-url: https://github.com/cct-datascience/group-procedures
  repo-actions: [edit]
  chapters:
    - index.qmd
    - part: general-info.qmd
      chapters:
        - code-of-conduct.qmd
        - onboarding.qmd
    - part: project-management.qmd
      chapters:
        - quarterly-meetings.qmd

format:
  html:
    code-copy: true
    theme: 
      light: flatly
      dark: darkly

bibliography: references.bib