project: 
  type: book
execute: 
  freeze: auto
book:
  title: "CCT Data Science Group Procedures"
  # cover-image: cover.png
  search: true
  site-url: https://cct-datascience.github.io/group-procedures/
  repo-url: https://github.com/cct-datascience/group-procedures
  repo-actions: [edit, issue, source]
  issue-url: https://github.com/cct-datascience/group-procedures/issues/new?template=suggest-edit.md
  chapters:
    - index.qmd
    - contributing.qmd
    - part: "General Information"
      chapters:
        - general-info.qmd
        - code-of-conduct.qmd
        - group-expectations.qmd
    - part: "Group Processes (Agile)"
      chapters:
        - project-management.qmd
        - standups.qmd
        - sprint-planning.qmd 
        - quarterly-meetings.qmd
        - annual-reviews.qmd
    - part: "Group Procedures"
      chapters:
        - onboarding.qmd
        - group-communication.qmd
        - hiring.qmd
        - professional-development.qmd
        - code-review.qmd
        - offboarding.qmd
    - part: "Group Programming"
      chapters:
        - drop-in-hours.qmd
        - incubator.qmd
        - workshops.qmd
    - part: "Resources"
      chapters: 
        - networking.qmd
        - software.qmd
        - use-gmail.qmd
    - part: "Technical Vignettes"
      chapters: 
        - vignettes_overview.qmd
        - publishing-to-web.qmd
        - creating-r-packages.qmd
        - spreadsheet-database-vignette.qmd
    - references.qmd

format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    code-copy: true
    theme: 
      light: flatly
      dark: darkly
      
editor: 
  markdown:
    wrap: sentence
    canonical: true
    
bibliography: references.bib
