---
title: "Annual Reviews"
editor: visual
---

Arizona Board of Regents requires at least one formal performance appraisal per year per employee.

The University of Arizona provides a standardized process called "[Career Conversations](https://hr.arizona.edu/career-conversations-employees)" that is described in more detail in the links below.
We will have Annual Reviews in early January each year, prior to the first Quarterly Review.

::: callout-note
Note that the University's career conversations cycle is on a different schedule than our groups.
You'll fill out your career conversations form at the end of the calendar year, but be required to submit it to HR at the end of the *fiscal* year in June.
:::

Steps:

1.  Define your personal goals for the year; SMART goals provide a helpful framework

2.  [Review what SMART Goals are](https://www.linkedin.com/learning/setting-team-and-employee-goals-using-smart-methodology/how-to-use-smart-goals-2)

3.  [SMART Goals Template](https://hr.arizona.edu/sites/default/files/Smart-Goal-Setting-Template_rev%202021.pdf)

4.  Fill out the [Career Conversations](https://hr.arizona.edu/career-conversations-employees) form.

5.  Send this form to David the day prior to your meeting.

*References:*

-   [Career Conversations Guide](https://hr.arizona.edu/career-conversations-employees)
-   [FAQs](https://hr.arizona.edu/career-conversations-employees) (at bottom of page)
