# Offboarding

## Overview

It is to everyone's advantage for career aspirations and changes in personnel to be an ongoing and open discussion.

The person who is leaving should inform Kristina as soon as they begin the process of looking for another position or are considering leaving.
Then discuss a plan for sharing with other members of the group.
The convention of giving two weeks notice is *not enough time to wrap up*.
With more time, the group can help with next steps including finding new positions and creating an exit plan.
Further, it typically takes a month or more to effectively document and transfer knowledge of what you are working on.

### Before final day

In approximately chronological order

-   Inform Kristina about what your last day will be
-   Review University of Arizona's [official "leaving" page](https://hr.arizona.edu/employees-affiliates/leaving-ua)
-   Write resignation letter for UA
    -   Kristina will send this and final date to HR & ALVSCE business office
-   Review two university checklists in Google Drive [offboarding folder](https://drive.google.com/drive/folders/1t__w3Lgrf7uju6SxXb0pGkfNE0LlTdFQ?usp=drive_link) and complete relevant tasks
-   Decide if you should become a DCC
    -   [UA DCC guidelines](https://hr.arizona.edu/employees/dccs)
    -   This might make sense if you are continuing collaborations with UA folks, or need to retain access to UA services such as email or Google Drive
    -   This process is initiated before leaving and can only be finalized after final day
-   Start to transfer relevant knowledge about projects and trainings
    -   This process could take a substantial amount of time
    -   Focus on bringing documentation up to date
    -   Meet with relevant people to transfer knowledge and train them as needed
-   Transition resources on digital accounts
    -   **Google Drive**
        -   Move all documents that could be useful for the group from your personal UA Google Drive to the UA CCT DS Google Drive
        -   Any docs you created in the UA CCT DS Google Drive should be accessible to rest of group; we all have default editor access
    -   **GitHub**
        -   Make a list of all repos you have contributed to for the group, in all organizations; if there are any repos in personal account, transfer them to our `cct-datascience` organization or another relevant collaborator
    -   **Posit Connect**
        -   For anything deployed to Connect, either add other team members as collaborators or document where the source document is (e.g. by adding a link to a GitHub repo in a Shiny app) so that others can deploy it later
    -   **HPC**
        -   Make sure all files are in the group folders, as you may lose access after your last day
    -   **toggl**
        -   Ensure time tracking is up to date as possible before leaving so we can have accurate project hours estimates
-   Leave contact information (e.g., personal email address) in case we need to reach you
- Schedule an exit interview with Kristina on or right before your last day

### After final day

-   Return university-owned equipment
    -   Includes computer equipment and books
    -   Either returned to Kristina or mailed to Forbes
-   Kristina should turn off person's Cat Card access to the second floor of BSRL
-   These should be done the week after someone's last day
    -   **GitHub**
        -   Kristina will change person's permissions to "outside collaborator" and review all group repos to change permissions if necessary
    -   **HackMD**
        -   In team space, remove person from member list
    -   **toggl**
        -   Deactivate user to open up more seats

### Exit Interview

We hope to have a culture of feedback that would prevent unresolved issues or an unexpected departure.
The exit interview provides a different context in which to to provide new feedback or reiterate previous feedback in a less constrained.

**Questions**:

Questions should be tailored to each individual situation.
Here are a few key questions:

-   How have you developed during your time on this team?
-   What did you like most about working on this team? What did you like the least?
-   How could the team have helped you more on the job?
-   What parts of the culture were a good fit for you? What changes would you suggest?
-   What was the most challenging part of this job?
-   Is there anything else that you would like to share?
