---
title: Onboarding
---

## Before you start

-   [ ] HR Paperwork
    -   [ ] Sign offer letter
    -   [ ] Complete I-9 verification
    -   [ ] Establish NetID [here](https://netid-portal.iam.arizona.edu/). You will receive an email with instructions.
    -   [ ] Log in to UAccess and complete the required tasks in the "New Employee Work-Center".
    -   [ ] Establish your UA email access.
    -   [ ] Anything else HR sends you, please complete promptly
-   [ ] Get CatCard
    -   The CatCard is your official UA employee identification.
    -   Get your cat card from the CatCard office in the ([Student Union](https://catcard.arizona.edu/obtain_catcard)) or [online](https://mycatcard.arizona.edu/)
    -   They can look up your employee number if you bring a driver's license or other form of ID.
-   [ ] Purchase equipment, either online or at campus bookstore, and set up your office.
    -   Each full time employee will be allocated:
        -   A computer, two monitors, a mouse/track pad/pointing device, a keyboards, and a docking station
        -   Enough outlets and ethernet ports to meet your needs. We can get additional routers / power strips as needed.
        -   Office supplies - there should be plenty of the basics: pens, pencils, paper, etc. If need more of anything, please ask.
    -   If you need anything further, just ask.
-   [ ] When your equipment arrives, complete a "University of Arizona Certification Statement For Off-Campus Location/Use of Equipment" (from HR).

## First Week

The goal in the first week is to set up your accounts and your physical and virtual workspaces, to meet others in the group and learn about our protocols, and to become familiar with the university.
Feel free to ask anyone in the group questions about these steps, especially in the group's Slack channel (#datascience channel within CALS CCT Slack).

-   [ ] Work through CCT-DS Onboarding checklist (this document). It's available as a GitHub issue [here](https://github.com/cct-datascience/group-procedures/issues/new?assignees=&labels=&projects=&template=onboarding-checklist.md&title=%5BYour+name%5D+Onboarding+checklist) so you can track your progress. Suggest changes, comment, and ask questions as you go to make it more useful to the next person.
-   [ ] Review our group's [Code of Conduct](code-of-conduct.qmd)

### HR logistics

-   [ ] Review the materials on the [New to the University of Arizona](https://hr.arizona.edu/employees-affiliates/new-ua) page
-   [ ] Work through the [New Employee Checklist](https://hr.arizona.edu/sites/default/files/New_Employee_Checklist.pdf)
-   [ ] Review the [Public Service Orientation](https://hr.arizona.edu/employees-affiliates/new-ua/new-employee-orientation-programs/arizona-public-service-orientation) and submit the [completion certificate](https://hr.arizona.edu/sites/default/files/hr/employees-affiliates/NewToTheUA/AZPSOrientation/certificate.pdf) to your HR representative (Rosalie).
-   [ ] Sign up for and attend a [Benefits Orientation](https://hr.arizona.edu/employees-affiliates/new-ua/new-employee-orientation-programs) *scheduled for 8/23*
-   [ ] Familiarize yourself with [Employee Resources](https://hr.arizona.edu/employees-affiliates/new-ua/employee-resources)
-   [ ] Complete required trainings in the [EDGE learning system](https://edgelearning.arizona.edu/?_gl=1*iko1z6*_ga*MTQyMTAyODIwOC4xNjg3OTYyMjcx*_ga_7PV3540XS3*MTY4OTA4NzIwMS4yMi4xLjE2ODkwODc2MTguMTguMC4w), which include IT security and preventing harassment & discrimination
    -   You may not be able to access EDGE until 24-48 hours after your official start date. You should complete these trainings within your first week on the job.
-   [ ] Complete your [benefits enrollment](https://hr.arizona.edu/employees-affiliates/benefits) in UAccess. You will receive instructions in your new hire emails.
    -   [ ] Select and enroll in a retirement plan. You need to enroll in retirment within 30 days of your start date.
    -   [ ] Once you have selected your retirement plan, you can sign up for other benefits. Enroll in other benefits within 31 days of starting.

### Internet

You should be on the university's VPN any time you connect to internet outside the UA.

-   [ ] Install Cisco Secure Client; instructions [here](https://uarizona.service-now.com/sp?id=sc_cat_item&sys_id=8ab35af01bb830507947edf1604bcb90).
    -   When asked for a third password/NetID+ method, input "push" or "sms" or "passcode" to autheticate via 2FA.
-   [ ] Log in to the VPN by opening Cisco Secure Client, typing in "vpn.arizona.edu/cals-ext", and clicking Connect. Then log in using your UA credentials and 2FA.

### Accounts access

Create accounts on the following collaboration tools (details provided below):

-   [ ] UA UITS Accounts, starting here: <https://account.arizona.edu/welcome>
    -   [ ] Email and calendar (Outlook or Gmail)
    -   [ ] Calendar (Outlook or Gmail)
    -   [ ] Google Apps
    -   [ ] Box
    -   [ ] HPC
        -   You need a "Research Sponsor" to request a HPC account. This is Kristina. When prompted, click on "Notify your sponsor of your request" and enter Kristina's UA email address.
    -   [ ] Zoom
        -   Download the desktop app and log in via SSO to get your Zoom room link
-   [ ] UA Office 365: <https://it.arizona.edu/service/microsoft-office-365>
-   [ ] Join Slack (used for most communication)
    -   [ ] CCT DS group (the #data-science channel within the CCT). You'll need an invite.
    -   [ ] [UA Data Science](https://jcoliver.github.io/uadatascience-slack/index), for broader DS community at University of Arizona
    -   [ ] [ResBaz](https://researchbazaar.arizona.edu/), community in Tucson for researchers using technology. You'll need an invite.
-   [ ] Request access to the group's shared Google Drive folders
-   [ ] GitHub setup
    -   [ ] If you already have an account that you wish to use for work, [add your UA email address to your account](https://github.com/settings/emails).
    -   [ ] If you don't already have an account sign up at (https://github.com), used to organize our work.
    -   [ ] Get added to our group's GitHub org: <https://github.com/cct-datascience>
    -   Note: We have two GitHub boards, one for [project management](https://github.com/orgs/cct-datascience/projects/8) and one for [incubators](https://github.com/orgs/cct-datascience/projects/7)
    -   See \[here\]\[1\] for more about 2FA for GitHub and access protocols
-   [ ] Join the group OSF, which is where we currently store group and project documentation
    -   [ ] Click here and follow instructions to sign up for an account on OSF <https://it.arizona.edu/service/open-science-framework-ua>
    -   [ ] Someone will have to add you as a contributor to our group's OSF page: <https://osf.io/emq9s/>
-   [ ] Join the [group Hackmd](https://hackmd.io/team/cct-datascience?nav=overview), used for a lot of group notetaking.
    -   [ ] You will need to create a Hackmd account, and then someone from the group will need to add you.
-   [ ] Get added to Toggl, for time tracking
-   [ ] Log in to get edit access to the website. Navigate to <https://datascience.cct.arizona.edu/user>. Don't log in using the obvious log in form; click on "Log in with NetAuth" (or similar) and log in using your NetID credentials.
-   [ ] Log in to [Stache](stache.arizona.edu), used for sharing passwords and other sensitive information within the university.
-   [ ] Get added to the group [Posit Connect](https://viz.datascience.arizona.edu/connect/)
    -   You'll have to request access and list a sponsor. This is Kristina.
-   [ ] Log in to the group [Quarto Pub](https://quartopub.com)

### Office space

-   [ ] After getting your Cat Card, fill out the form at https://access.bio5.org/ to request access to BSRL
    -   Click on request access for Data7
    -   There is a cafe in first floor lobby with coffee and food for purchase.

### Publicity!

-   [ ] Send Kristina a headshot to use for your page on the website.
-   [ ] Write a short blog post (Renata's is [here](https://datascience.cct.arizona.edu/news/2023/08/renata-diaz-joins-cct-data-science-team) and Eric's is [here](https://datascience.cct.arizona.edu/news/2022/06/welcome-eric-scott)) announcing that you've joined the team.
-   [ ] Write and update your blurb on your page on the website.
-   [ ] Also send Headshot, Bio, Links to Matt Rahr (rahr\@ag.arizona.edu) in CCT
-   [ ] Make a Mastodon post.
-   [ ] (Optional) Update your social bios, etc.

### Integrating into group workflows

-   [ ] Read about group expectations and general information [here](https://osf.io/tzmhp/wiki/General%20Information/)
-   [ ] Populate your calendar with the current group meeting schedule. Kristina will send you invites.
-   [ ] Participate in daily standup meetings, [biweekly sprint planning meetings](https://hackmd.io/ih-qR2B6RJ221MJEFeEqcA), [weekly outreach hour](https://hackmd.io/fxo335XYQXGUpIm6c46TkQ), and [biweekly incubator meetings](https://github.com/orgs/cct-datascience/projects/7). Review [project management OSF page](https://osf.io/tzmhp/wiki/Project%20Management/) to prepare for these.
-   [ ] Set up your standing meeting with Kristina.
-   [ ] Begin learning about and using software and data related to projects.
    -   This can include reading about incubators (on our GitHub project board), funded projects (talk to Kristina and current team members), or trainings.
-   [ ] Fill out biweekly time sheets every other Friday morning by 10am AZ on [UAccess](https://uaccess.arizona.edu/), which also has pay stubs, insurance info, etc.
    -   If you are salaried, you only need to put in 1 hour of "PAW - Present at Work" for the pay period (doesn't matter which week), and then record any *exception* time (sick/vacation/jury duty). You don't need to enter all of your regular work hours.
    -   Holidays and university closures will be automatically added to your time sheet.

## Second Week

-   [ ] Discuss OKRs and review [OKR overview slides](https://drive.google.com/open?id=1wZBYlYZK4s2HPJAjNqR9-9RXQUY3KGbK "OKR Introduction") with Kristina.
    -   Review Group Objectives and Key Results
    -   Identify 3-4 Objectives with 3-4 Key Results (\<=12 total) for your first Quarter using the template; [see Q3 2019](https://docs.google.com/spreadsheets/d/18ANZGFdBHBU8l9WbFTE0fErcCaTva3LyazuhAex4FFE/edit#gid=129820665)
-   [ ] Add your skills to the [group skills matrix](https://docs.google.com/spreadsheets/d/1N95GgtAgvpQ9PhpiYwqWYewWu-FOzeIoQxzX2oldUuk/edit?usp=sharing)
-   [ ] Read [Best Practices in Scientific Computing](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1001745)
-   [ ] Order business cards: <https://brand.arizona.edu/stationery>

## First Month

Objective is to familiarize yourself with the specific project(s) that you will be working on, including:

-   Project(s) background, platforms, setup, and purpose
-   The software stack that you will be working on
-   People, proposals, scientific literature, and other elements of project(s) that you will work on
-   Identify the skills you will need (and want) to build on in your first year
-   Other objectives that are specific to your role, which can be determined by working with your supervisor and other project members

**People to Meet / Know**

This depends on what you're working on, but it is useful to know and have chatted with at least some of these people:

-   CyVerse / Data7
    -   Matt Rahr (Director, CCT)
    -   Maliaca Oxnam (Deputy Director, Data Science Institute)
    -   Ellen Bledsoe (SNRE)
    -   Jeff Oliver (Library)
    -   Nirav Marchant (CyVerse, Data Science Institute)
    -   Tyson Swetnam (CyVerse)
    -   Rachel and Conroy (IRL, BSRL Custodians)
-   Project Collaborators
    -   Co-PIs, students, staff involved in projects that you are working on.
