---
title: Professional Development
---

# Professional Development

I encourage all group member to attend (at least)

-   One conference or workshop per year. Our group's mission is inherently collaborative, and this outreach is important.
-   Seminars, webinars, and classes that will help you gain skills and knowledge related to your current work or work that you would like to do. For example:
-   On Campus: TRIPODS ecosystem genomics, data7 seminars, phenomics)
-   [Posit Webinars](https://posit.co/resources/videos/)
-   Help writing grants and papers.
    -   (Learn) and use the [Pivot](https://pivot-proquest-com.ezproxy3.library.arizona.edu/funding_main) database to identify opportunities.

The University of Arizona provides a number of professional development opportunities.

-   <https://ce.arizona.edu/professional-development>

-   Funding: you have the opportunity to **seek external funding** - this will help with your professional development and our bottom line.

-   All University of Arizona employees age 21-45 should consider joining "Tucson Young Professionals".
    The U of A covers membership fees (normally \$200/y) - see [this website for more information](https://olod.arizona.edu/typ)).


# Publishing \[Under construction\]

Documentation, GitHub threads, Slack Discussions are all great places to find inspiration for publishable units; peer reviewed publications help provide an academic foundation for our group's contributions, with outreach as well as future funding.

### Papers and Conference Proceedings

### Data

### Software

-   Zenodo: Major releases should get a doi here; can set up a github hook to archive each release.
-   Journal of Open Source Software: JOSS <https://joss.theoj.org/>
