---
title: "Standups"
editor: visual
---

### Daily Standups

We meet daily at 9:50 AM (unless we have a sprint planning or retrospective meeting that day) for approximately ten minutes.
The team member who leads the meeting is a rotating role that can be found [here](https://docs.google.com/spreadsheets/d/1k4B59FdpGxAd2sNrgbXRLrYIVgcxjvnYF5yJoaIcOAA/edit?usp=sharing).
The leader is responsible for keeping the Standup on track and on time.
Everyone answers the following questions:

-   What did you do yesterday?

-   What are you planning to do today?

-   **Is anything blocking your work?**

This often leads to more indepth discussions which should be identified as tangential.
The leader or any other team memember should suggest that the participants continue their discussion after the meeting or at a different time.

### Weekly Individual Meetings

Everyone meets once per week with Kristina for a 30 minute one-on-one.
Once a month, this meeting is extended to an hour to discuss OKR's.

### Weekly Writing Hour

We meet once per week (currently on Fridays from 11 am to noon on [Zoom](https://arizona.zoom.us/j/95331103083?p=5bGA0w)) to dedicate time to writing tasks.
Notes are recorded [here](https://hackmd.io/fxo335XYQXGUpIm6c46TkQ).
We use the Pomadoro method of writing for 25 minutes followed by a 5 minute break to review progress.
Writing tasks can be found [here](https://github.com/az-digitalag/organization/labels/writing).
