name: Links

on:
  pull_request:
  workflow_dispatch:
  schedule:
  #every monday
    - cron: "0 0 * * MON"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          fail: true
          args: --glob-ignore-case --exclude docs\.google\.com --exclude hackmd\.io --exclude github\.com\/orgs\/cct-datascience\/projects './**/*.md' './**/*.qmd'

      - name: Create Issue From File
        if: env.lychee_exit_code != 0 & ${{ github.event_name != 'pull_request' }}
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue